# Generated by Django 4.2.7 on 2025-01-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Usuario')], default=2),
        ),
    ]
